# Generated by Django 3.2 on 2021-05-01 13:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Customer', '0003_rename_mobile_no_customer_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('open_date', models.DateField()),
                ('account_type', models.CharField(max_length=10)),
                ('cards', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=2)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
            options={
                'db_table': 'bankaccount',
            },
        ),
    ]
