# Generated by Django 3.2 on 2021-05-01 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0004_alter_bankaccount_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='cards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=2),
        ),
    ]
