# Generated by Django 3.2 on 2021-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfname', models.CharField(max_length=50)),
                ('cmname', models.CharField(max_length=50, null=True)),
                ('clname', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
                ('dateof_birth', models.DateField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
