# Generated by Django 3.2 on 2021-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_rename_mobile_no_customer_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Signature',
            field=models.ImageField(default='default.jpg', upload_to='signatures/'),
        ),
    ]
