# Generated by Django 3.2 on 2021-05-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20210502_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Signature',
            field=models.ImageField(blank=True, db_column='Signature', null=True, upload_to='signatures/'),
        ),
    ]
