# Generated by Django 3.2 on 2021-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20210502_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
